---
- name: Add Docker repository
  become: true
  ansible.builtin.shell: printf "%s\n" "deb [arch=amd64] https://download.docker.com/linux/debian buster stable" | tee /etc/apt/sources.list.d/docker-ce.list

- name: Add Docker GPG key
  become: true
  ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

- name: Install Docker
  become: true
  ansible.builtin.shell: apt update && apt install -y docker-ce docker-compose-plugin

- name: Download Bloodhound CLI
  become: true
  ansible.builtin.shell: wget https://github.com/SpecterOps/bloodhound-cli/releases/latest/download/bloodhound-cli-linux-amd64.tar.gz

- name: Untar Bloodhound CLI
  become: true
  ansible.builtin.shell: tar -xvzf bloodhound-cli-linux-amd64.tar.gz

- name: Set default Bloodhound admin password
  become: true
  ansible.builtin.shell: ./bloodhound-cli config set default_admin.password "{{ general.attack_range_password }}"
  
- name: Set default Bloodhound password
  become: true
  ansible.builtin.shell: ./bloodhound-cli config set default_password "{{ general.attack_range_password }}"

- name: Install Bloodhound
  become: true
  ansible.builtin.shell: ./bloodhound-cli install
