---
- name: Install Docker
  become: true
  ansible.builtin.shell: apt update && apt install -y curl && curl -L get.docker.com | bash

- name: Download Bloodhound CLI
  become: true
  ansible.builtin.shell: wget https://github.com/SpecterOps/bloodhound-cli/releases/latest/download/bloodhound-cli-linux-amd64.tar.gz

- name: Untar Bloodhound CLI
  become: true
  ansible.builtin.shell: tar -xvzf bloodhound-cli-linux-amd64.tar.gz

- name: Set default Bloodhound admin password
  become: true
  ansible.builtin.shell: ./bloodhound-cli config set default_admin.password "{{ general.attack_range_password }}"
  
- name: Set default Bloodhound password
  become: true
  ansible.builtin.shell: ./bloodhound-cli config set default_password "{{ general.attack_range_password }}"

- name: Install Bloodhound
  become: true
  ansible.builtin.shell: ./bloodhound-cli install
