---

- name: copy emulation.md
  copy:
    src: emulation.md
    dest: /home/kali/emulation.md
    force: yes

- name: Give everyone persmissions on emulation.md
  become: true
  ansible.builtin.shell: chmod 777 /home/kali/emulation.md

- name: install pandoc
  become: true
  apt:
    name:  pandoc
    state: latest
    update_cache: yes

- name: convert markdown emulation to html and place it as Mozilla homepage
  become: true
  ansible.builtin.shell: pandoc -f markdown /home/kali/emulation.md > /usr/share/kali-defaults/web/homepage.html

- name: copy StartHere.html
  copy:
    src: StartHere.html
    dest: /home/kali/Desktop/StartHere.html
    force: yes

- name: Set perms on StartHere.html
  become: true
  ansible.builtin.shell: chmod 777 /home/kali/Desktop/StartHere.html
