---

- name: Copy join domain script to host
  win_copy:
    src: "populate-ad.ps1"
    dest: 'C:\populate.ps1'

- name: Run join domain
  win_shell: "C:\\populate.ps1 attackrange.local 20 {{ ansible_user }}@attackrange.local {{ general.attack_range_password }}"
  register: win_shell_output
  retries: 20
  delay: 60
  until: win_shell_output.stderr == ""

- debug:
    var: win_shell_output
